stages:
  - build
  - deploy

build:
  image: klakegg/hugo:0.79.1-alpine-ci
  stage: build
  script:
    - hugo --ignoreCache --minify --verbose --debug
  artifacts:
    paths:
      - public/

deploy:
  image: devillex/docker-firebase:slim
  stage: deploy
  when: manual
  only:
    - master
  script:
    - firebase use personal-page-cf8ad --token $FIREBASE_TOKEN
    - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN
  environment:
    name: production
    url: https://rhazn.com
  dependencies:
    - build
