baseURL = "https://rhazn.com"
languageCode = "en-us"
title = "rhazn.com"
googleAnalytics = "UA-109574740-3"
theme = "pulp"
canonifyurls = true
enableRobotsTXT = true

[params]
    author = "Philip Heltweg"
    avatar = "avatar.jpg"
    # not used, see custom partial head
    favicon = "favicon.ico"
    description = """
        work in progress person

    """
    publicationYear = "2020"
    # listPageDateFormat = "January, 2006" # See https://gohugo.io/functions/format/
    # singlePageDateFormat = "January 2, 2006"
    custom_css = ["/css/custom.css"]
    # custom_js = ["/js/custom.js"]

# Make sure setting a following option for search bar to work
[outputs]
    section = ["JSON", "HTML"]
    taxonomy = ["JSON", "HTML"]

[[menu.main]]
    identifier = "blog"
    name = "Blog" #If display text link, cancel comment out
    pre = "<i class='fa fa-book-open fa-lg'></i>" #Choose your favorite font from Font Awesome
    url = "/posts/"
    weight = 10

[[menu.main]]
    identifier = "projects"
    name = "Projects" #If display text link, cancel comment out
    pre = "<i class='fa fa-project-diagram fa-lg'></i>" #Choose your favorite font from Font Awesome
    url = "/projects/"
    weight = 20

[[menu.main]]
    identifier = "email"
    name = "Email"
    pre = "<i class='fa fa-envelope fa-lg'></i>"
    url = "mailto:pheltweg@gmail.com"
    weight = 30

[[menu.main]]
    identifier = "cv"
    name = "CV"
    pre = "<i class='fa fa-file-download fa-lg'></i>"
    url = "/files/cv_philip_heltweg.pdf"
    weight = 40