baseURL = "https://rhazn.com"
languageCode = "en-us"
title = "rhazn.com"
googleAnalytics = "UA-109574740-3"
theme = "pulp"
canonifyurls = true
enableRobotsTXT = true

[params]
    author = "Philip Heltweg"
    avatar = "avatar.jpg"
    favicon = "favicon.ico"
    description = """
        not all those who wander are lost
    """
    publicationYear = "2019"
    # listPageDateFormat = "January, 2006" # See https://gohugo.io/functions/format/
    # singlePageDateFormat = "January 2, 2006"
    custom_css = ["/css/custom.css"]
    # custom_js = ["/js/custom.js"]

[outputs]
    section = ["JSON", "HTML"]

[[menu.main]]
    identifier = "blog"
    # name = "Blog" #If display text link, cancel comment out
    pre = "<i class='fa fa-book-open fa-lg'></i>" #Choose your favorite font from Font Awesome
    url = "/posts/"
    weight = 10

[[menu.main]]
    identifier = "twitter"
    # name = "Twitter"
    pre = "<i class='fab fa-twitter fa-lg'></i>"
    url = "https://twitter.com/rhanarion"
    weight = 20

[[menu.main]]
    identifier = "email"
    # name = "Email"
    pre = "<i class='fa fa-envelope fa-lg'></i>"
    url = "mailto:pheltweg@gmail.com"
    weight = 40