baseURL: "https://heltweg.org"
title: Philip Heltweg
paginate: 10
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

permalinks:
    posts: /posts/:slug
    projects: /projects/:slug

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Philip Heltweg
    description: "work in progress person"
    author: Philip Heltweg
    # author: ["Me", "You"] # multiple authors
    images: ["/img/avatar2.jpeg"] # <link or path of image for opengraph, twitter-cards>

    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowWordCount: true
    ShowRssButtonInSectionTermList: true
    UseHugoToc: false
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: true
    draft: false
    hidemeta: false
    hideSummary: false
    showtoc: true
    tocopen: true
    ShowReadingTime: true

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "/img/favicon/favicon.ico"
        favicon16x16: "/img/favicon/favicon-16x16.png"
        favicon32x32: "/img/favicon/favicon-32x32.png"
        apple_touch_icon: "/img/favicon/apple-touch-icon.png"
        safari_pinned_tab: "/img/favicon/safari-pinned-tab.svg"

    label:
        text: "Home"
        icon: /img/favicon/apple-touch-icon.png
        iconHeight: 35

    homeInfoParams: # Overwritten in layouts/partials/home_info.html
        Title: Hi, I am Philip 👋
        Content: # Overwritten in layouts/partials/home_info.html

    socialIcons:
        - name: email
          url: "mailto:philip@heltweg.org"
        - name: github
          url: "https://github.com/rhazn"
        - name: mastodon
          url: "https://mas.to/@rhazn"
        - name: twitter
          url: "https://twitter.com/rhanarion"
        - name: discord
          url: "https://discordapp.com/users/148739214660468736"
        - name: telegram
          url: "https://t.me/rhanarion"
        - name: linkedin
          url: "https://www.linkedin.com/in/pheltweg"
        - name: cv
          url: "/files/cv_philip_heltweg.pdf"

    #analytics:
    #    google:
    #        SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        includeMatches: true
        location: 0
        distance: 1000
        threshold: 0.3
        minMatchCharLength: 3
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: posts
          name: All Posts
          url: /posts/
          weight: 10
        - identifier: search
          name: Search
          url: /search/
          weight: 30
        - identifier: cv
          name: CV
          url: /files/cv_philip_heltweg.pdf
          weight: 40

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
#pygmentsUseClasses: true
markup:
    goldmark:
        renderer:
            unsafe: true
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai

# for search
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary